"""Shared prompt format for the small-model harness (training and inference must match).

Adapted from the prompt used in the teammate's ~/Downloads/finetuine/mat/common.py.
Essays are not generated by the model: they come from the prepared essay bank.
"""
import re
from collections import Counter

SYSTEM = ("Jesteś egzaminatorem-ekspertem i najlepszym maturzystą z historii (matura CKE, poziom rozszerzony). "
          "Rozwiązujesz jedno zadanie. Czytasz polecenie, wszystkie źródła i ilustracje. "
          "Piszesz po polsku wyłącznie ostateczną odpowiedź, bez rozumowania i wstępów. "
          "Jeśli polecenie kończy się etykietami (np. 'Rozstrzygnięcie:' i 'Uzasadnienie:'), powtórz je i uzupełnij każdą. "
          "W zadaniach zamkniętych trzymaj się dokładnie składni z pola 'Format odpowiedzi'. "
          "W zadaniach otwartych podaj konkretne fakty (nazwy, daty, pojęcia), odwołaj się do źródła i do własnej wiedzy, gdy polecenie tego wymaga.")

OPEN_FORMAT = "Tekst po polsku. Podaj wszystkie wymagane elementy odpowiedzi."
ESSAY_FORMAT = "Jeden tekst: numer wybranego tematu i całe wypracowanie. Minimum 300 wyrazów zgodnie z poleceniem."


def kind(item):
    af = (item.get("answer_format") or "").strip()
    if int(item.get("max_points") or 0) >= 10 or af.startswith("Jeden tekst"):
        return "essay"
    if af.startswith("Tekst"):
        return "open"
    return "closed"


def user_text(item, context=None):
    parts = []
    if context:
        parts.append("Materiały pomocnicze (fragmenty encyklopedii, mogą być nieistotne):\n" + context.strip())
    if (item.get("source_text") or "").strip():
        parts.append("Źródła:\n" + item["source_text"].strip())
    parts.append("Polecenie:\n" + item["question"].strip())
    parts.append("Format odpowiedzi:\n" + (item.get("answer_format") or OPEN_FORMAT).strip())
    return "\n\n".join(parts)


def messages(item, context=None):
    return [{"role": "system", "content": SYSTEM}, {"role": "user", "content": user_text(item, context)}]


LINE = re.compile(r"^([0-9A-Za-z]{1,3})\s*[:.)]\s*(.+)$")


def vote_closed(answers):
    """Per-line majority vote for closed answers like '1: P\\n2: F' or a single letter."""
    keyed, order, plain = {}, [], Counter()
    for a in answers:
        lines = [l.strip() for l in a.strip().splitlines() if l.strip()]
        m = [LINE.match(l) for l in lines]
        if lines and all(m):
            for mm in m:
                k, v = mm.group(1), mm.group(2).strip()
                if k not in keyed:
                    keyed[k] = Counter(); order.append(k)
                keyed[k][v] += 1
        else:
            plain[a.strip()] += 1
    if keyed and sum(sum(c.values()) for c in keyed.values()) >= sum(plain.values()):
        return "\n".join(f"{k}: {keyed[k].most_common(1)[0][0]}" for k in order)
    return plain.most_common(1)[0][0] if plain else answers[0]


def medoid(answers):
    """Sample most similar to the others (word-set Jaccard)."""
    sets = [set(re.findall(r"\w+", a.lower())) for a in answers]
    def sim(i, j):
        u = sets[i] | sets[j]
        return len(sets[i] & sets[j]) / len(u) if u else 0.0
    return answers[max(range(len(answers)), key=lambda i: sum(sim(i, j) for j in range(len(answers)) if j != i))]
